blog/urls.py
from django.urls import path

from .views import (
    posts_view,
    like,
)

app_name = 'blog'

urlpatterns = [
    path('', posts_view, name='posts'),
    
    path('like/<int:pk>', like, name='like')
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static


from django.contrib import admin
from django.urls import path, include

from .views import (
    register_view,
    login_view,
    logout_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    
    path('', include('blog.urls', namespace='blog')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.shortcuts import reverse

from django.contrib.auth.models import User

# Create your models here.

class PostModel(models.Model):
    content = models.TextField()
    image = models.ImageField(upload_to='blog/images/', blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    publish_date = models.DateTimeField(auto_now_add=True)
    
    
    class Meta:
        ordering = ['-publish_date']
    
    def __str__(self):
        return self.author.username
    
    @property
    def get_like_count(self):
        return self.like_set.all().count()
        

class Like(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(PostModel, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.author.username
    

blog/forms.py
from django import forms

from .models import PostModel

class PostFrom(forms.ModelForm):
    content = forms.CharField(
        widget=forms.Textarea(
        attrs={
            'class':'w-full px-0 text-sm text-gray-900 bg-white border-0 focus:ring-0',
            'rows':2,
            'placeholder':'Write a comment...'
            }
        ),
        required=True,
    )
    
    image = forms.ImageField(
        required=False,
    )
    
    class Meta:
        model = PostModel
        fields = ['content', 'image']

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, User

class UserRegisterFrom(UserCreationForm):
    username = forms.CharField(
        label="Username",
        widget=forms.TextInput(
        attrs={'class':'mb-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'}),
        required=True
    )
    
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
        attrs={'class':'mb-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'}),
        required=True
    )
    
    password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(
        attrs={'class':'mb-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'}),
        required=True
    )
    
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        help_texts = {k:"" for k in fields}

class LoginUser(AuthenticationForm):
    username = forms.CharField(
        label="Username",
        widget=forms.TextInput(
        attrs={'class':'mb-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'}),
        required=True
    )
    
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
        attrs={'class':'mb-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'}),
        required=True
    )
    
    class Meta:
        model = User
        fields = ['username', 'password1']

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import PostModel, Like
from .forms import PostFrom

# Create your views here.


@login_required
def posts_view(request):
    posts = PostModel.objects.all()
    form = PostFrom(request.POST or None, request.FILES)
        
    likes = Like.objects.filter(author=request.user)
    
     # Agregar información de likes a cada post
    for post in posts:
        post.user_like = likes.filter(post=post).first()
    
    if request.method == "POST":
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.author = request.user
            new_user.save()
            messages.success(request, 'Post published successfully!')
            return redirect('blog:posts')
        
        else:
            messages.warning(request, 'data not valid!')

    return render(request, 'pages/blog/posts.html', context={
        'posts' : posts,
        'form' : form,
    })

@login_required
def like(request, pk):
    post = get_object_or_404(PostModel, pk=pk)
    like_qs = Like.objects.filter(author=request.user, post=post)

    if like_qs.exists():
        like_qs[0].delete()
    else:
        Like.objects.create(author=request.user, post=post)

    return redirect('blog:posts')

core/views.py
from django.shortcuts import render, redirect
from django.db import IntegrityError
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages

from .forms import UserRegisterFrom, LoginUser


def register_view(request):
    if request.method == 'GET':
        return render(request, 'pages/register.html', context={
            'form' : UserRegisterFrom,
        })
        
    else:
        if request.POST['password1'] == request.POST['password2']:
            
            try:
                user = User.objects.create_user(username=request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                messages.success(request, 'User registered successfully!')
                return redirect('blog:posts')
            
            except IntegrityError:
                messages.warning(request, 'User already exists')
                return render(request, 'pages/register.html', context={
                    'form' : UserRegisterFrom,
                })
          
        messages.warning(request, 'Password not match!')      
        return render(request, 'pages/register.html', context={
            'form' : UserRegisterFrom,
        })
    

def login_view(request):
    if request.method == 'GET':
        return render(request, 'pages/login.html', context={
            'form' : LoginUser,
        })
    
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.warning(request, 'Username or Password incorrect')
            return render(request, 'pages/login.html', context={
                    'form' : LoginUser,
                })
        else:
            login(request, user)
            return redirect('blog:posts')

def logout_view(request):
    logout(request)
    return redirect('login')

templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>News</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
		<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
		<!--Alpine JS-->
		<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.8.2/dist/alpine.min.js" defer></script>
	</head>

	<body>
        {% block navbar %}{% endblock navbar %}

		{% include 'components/messages.html' %}

        {% block content %}{% endblock content %}

	</body>
</html>

templates/components/messages.html
{% if messages %}
    {% for message in messages %}
    <div x-data="{ open: true }" @keydown.window.escape="open = false"  x-show="open" class="fixed z-10 inset-0 overflow-y-auto" aria-labelledby="modal-title" x-ref="dialog" aria-modal="true">
        <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
            <div x-show="open" x-transition:enter="ease-out duration-300" x-transition:enter-start="opacity-0" x-transition:enter-end="opacity-100" x-transition:leave="ease-in duration-200" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0" x-description="Background overlay, show/hide based on modal state." class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" @click="open = false" aria-hidden="true"></div>
    
            <!-- This element is to trick the browser into centering the modal contents. -->
            <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">​</span>
            
            <div x-show="open" x-transition:enter="ease-out duration-300" x-transition:enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95" x-transition:enter-end="opacity-100 translate-y-0 sm:scale-100" x-transition:leave="ease-in duration-200" x-transition:leave-start="opacity-100 translate-y-0 sm:scale-100" x-transition:leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95" x-description="Modal panel, show/hide based on modal state." class="inline-block align-bottom dark:bg-dark-second bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-sm sm:w-full sm:p-6">
                <div>
                {% if message.tags == 'success' %}
                <div class="mx-auto flex items-center justify-center h-12 w-12 rounded-full bg-green-100">
                    <svg class="h-6 w-6 text-green-500" x-description="Heroicon name: outline/check" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
                    </svg>
                </div>
                {% else %}
                <div class="mx-auto flex items-center justify-center h-12 w-12 rounded-full bg-green-100">
                    <svg class="h-6 w-6 text-red-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
                    </svg>
                </div>
                {% endif %}                
                <div class="mt-3 text-center sm:mt-5">
                    <h3 class="text-lg leading-6 font-medium dark:text-dark-txt text-gray-900" id="modal-title">
                    {{ message.tags }}
                    </h3>
                    <div class="mt-2">
                    <p class="text-sm  dark:text-dark-txt text-gray-500">
                    {{ message }}
                    </p>
                    </div>
                </div>
                </div>
                <div class="mt-5 sm:mt-6">
                <button type="button" class="inline-flex justify-center w-full rounded-md border border-transparent shadow-sm px-4 py-2 bg-blue-500 text-base font-medium text-white hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 sm:text-sm" @click="open = false">
                    Ok
                </button>
                </div>
            </div>
            
        </div>
    </div>
    {% endfor %}
{% endif %}

templates/components/navbar.html
{% load static %}

<header class="sticky inset-0 z-50 border-b border-slate-100 bg-white/80 backdrop-blur-lg">
    <nav  class="mx-auto flex max-w-6xl gap-8 px-6 transition-all duration-200 ease-in-out lg:px-12 py-4">
        <div class="relative flex items-center">
            <a href="{% url 'blog:posts' %}">
                <img  src="https://www.svgrepo.com/show/499831/target.svg" loading="lazy" style="color:transparent" width="32" height="32">
            </a>
            {% if request.user.is_authenticated %}
                <p class="ml-2"> @{{ request.user.username }} </p>
            {% endif %}
        </div>
        
{% comment %}         <ul class="hidden items-center justify-center gap-6 md:flex">
            {% if request.user.is_authenticated %}
                    <li class="pt-1.5 font-dm text-sm font-medium text-slate-700">
                        <a href="{% url 'blog:posts' %}">Blog</a>
                    </li>

                </ul> {% endcomment %}

            {% if request.user.is_authenticated %}    
                <div class="flex-grow"></div>
                {% comment %} <div class="hidden items-center justify-center gap-6 md:flex"> {% endcomment %}
                    <div class="items-center justify-center gap-6">
                    <a href="{% url 'logout' %}"
                        class="rounded-md bg-gradient-to-br from-green-600 to-emerald-400 px-3 py-1.5 font-dm text-sm font-medium text-white shadow-md shadow-green-400/50 transition-transform duration-200 ease-in-out hover:scale-[1.03]">
                        Logout
                    </a>
                </div>
            {% else %}
                </ul>
                <div class="flex-grow"></div>
                {% comment %} <div class="hidden items-center justify-center gap-6 md:flex"> {% endcomment %}
                    <div class="items-center justify-center gap-6">
                    <a href="{% url 'register' %}" class="mr-4 font-dm text-sm font-medium text-slate-700">SignUp</a>
                    <a href="{% url 'login' %}"
                        class="rounded-md bg-gradient-to-br from-green-600 to-emerald-400 px-3 py-1.5 font-dm text-sm font-medium text-white shadow-md shadow-green-400/50 transition-transform duration-200 ease-in-out hover:scale-[1.03]">
                        SignIn
                    </a>
                </div>
            {% endif %}
            {% comment %} <div class="relative flex items-center justify-center md:hidden">
                <button type="button">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" class="h-6 w-auto text-slate-900"><path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"></path></svg>
                </button>
            </div> {% endcomment %}
    </nav>
</header>

templates/pages/blog/posts.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock navbar %}

{% block content %}
 


<form method="POST" action="{% url 'blog:posts' %}" enctype="multipart/form-data" class="w-11/12  m-auto mt-2">
    {% csrf_token %}
    <div class="w-full mb-4 border border-gray-200 rounded-lg bg-gray-50">
        <div class="flex px-4 py-2 bg-white rounded-t-lg">
            <img src="#" style="display:none;" class="h-auto w-28 rounded-lg mr-2" alt="" id="previewImage">
            {{form.content}}
        </div>
        
        <div class="flex items-center justify-between px-3 py-2 border-t">
            <button type="submit" class="inline-flex items-center py-2.5 px-4 text-xs font-medium text-center text-white bg-blue-700 rounded-lg focus:ring-4 focus:ring-blue-200 hover:bg-blue-800">
                Post comment
            </button>
            <div class="flex ps-0 space-x-1 rtl:space-x-reverse sm:ps-2">
                <label for="id_image" class="inline-flex justify-center items-center p-2 text-gray-500 rounded cursor-pointer hover:text-gray-900 hover:bg-gray-100">
                <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 18">
                    <path d="M18 0H2a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2Zm-5.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Zm4.376 10.481A1 1 0 0 1 16 15H4a1 1 0 0 1-.895-1.447l3.5-7A1 1 0 0 1 7.468 6a.965.965 0 0 1 .9.5l2.775 4.757 1.546-1.887a1 1 0 0 1 1.618.1l2.541 4a1 1 0 0 1 .028 1.011Z"/>
                </svg>
                <div style="display:none;">
                    {{ form.image }}
                </div>
                </label>
            </div>
        </div>
    </div>
</form>

<div class="mt-12 w-7/12 mx-auto">
  
    {% for post in posts %}

    <div class="flex flex-col rounded-lg shadow-2xl overflow-hidden mb-6">
      {% if post.image %}
      <div class="flex-shrink-0">
        <img class="h-50 w-full object-cover" src="{{post.image.url}}" alt="">
      </div>
     {% endif %}

      <div class="flex-1 bg-white p-6 flex flex-col justify-between">
        
        <div class="flex items-center justify-between">
          <div class="">
            <p class="text-sm font-medium text-gray-900">
              <a href="#" class="hover:underline">
                @{{ post.author.username }}
              </a>
            </p>
            <div class="text-sm text-gray-500">
              <span>
                {{ post.publish_date|timesince }} ago
              </span>
            </div>
          </div>
        </div>

        <div class="flex-1">
            <p class="block mt-3 text-base text-gray-500">
              {{post.content}}
            </p>
        </div>

        <div class="flex items-center">
          {% if post.user_like %}
            <a href="{% url 'blog:like' post.id %}" class="mt-2 inline">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
                <path d="M11.645 20.91l-.007-.003-.022-.012a15.247 15.247 0 01-.383-.218 25.18 25.18 0 01-4.244-3.17C4.688 15.36 2.25 12.174 2.25 8.25 2.25 5.322 4.714 3 7.688 3A5.5 5.5 0 0112 5.052 5.5 5.5 0 0116.313 3c2.973 0 5.437 2.322 5.437 5.25 0 3.925-2.438 7.111-4.739 9.256a25.175 25.175 0 01-4.244 3.17 15.247 15.247 0 01-.383.219l-.022.012-.007.004-.003.001a.752.752 0 01-.704 0l-.003-.001z" />
              </svg>
            </a>
          {% else %}
            <a href="{% url 'blog:like' post.id %}" class="mt-2 inline">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
              </svg>              
            </a>
          {% endif %}

          <div class="flex ps-0 mt-2 space-x-1 rtl:space-x-reverse sm:ps-2">
            <p class="text-base text-gray-500">
              {{ post.get_like_count }}
            </p> 
          </div>

      </div>

      </div>
    </div>
    {% endfor %}
    
    

  </div>

</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="{% static 'app.js' %}"></script>

{% endblock content %}

templates/pages/login.html
{% extends 'base.html' %}

{% block navbar %}
{% include 'components/navbar.html' %}
{% endblock navbar %}

{% block content %}

{{ error }}

  <div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
    <div class="sm:mx-auto sm:w-full sm:max-w-sm">
      {% comment %} <img class="mx-auto h-10 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="Your Company"> {% endcomment %}
      <h2 class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">Sign in to your account</h2>
    </div>
  
    <div class="sm:mx-auto sm:w-full sm:max-w-sm">
      <form class="space-y-6" action="#" method="POST">
        {% csrf_token %}
        
        <div>
          <label for="id_username" class="block text-sm font-medium leading-6 text-gray-900">Username</label>
          <div class="mt-2">
           {{ form.username }}
          </div>
        </div>

        <div>
          <label for="id_password" class="mt-2 block text-sm font-medium leading-6 text-gray-900">Password</label>
          <div class="mt-2">
           {{ form.password }}
          </div>
        </div>

        <div class="mt-2">
          <button type="submit" class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Login</button>
        </div>
      </form>
    </div>
  </div>

  

{% endblock content %}

templates/pages/register.html
{% extends 'base.html' %}

{% block navbar %}
{% include 'components/navbar.html' %}
{% endblock navbar %}

{% block content %}

{{ error }}

<div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
    <div class="sm:mx-auto sm:w-full sm:max-w-sm">
      {% comment %} <img class="mx-auto h-10 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="Your Company"> {% endcomment %}
      <h2 class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">Register in  account</h2>
    </div>
  
    <div class="sm:mx-auto sm:w-full sm:max-w-sm">
      <form class="space-y-6" action="#" method="POST">
        {% csrf_token %}
        
        <div>
          <label for="id_username" class="block text-sm font-medium leading-6 text-gray-900">Username</label>
          <div class="mt-2">
           {{ form.username }}
          </div>
        </div>

        <div>
          <label for="id_password1" class="block text-sm font-medium leading-6 text-gray-900">Password</label>
          <div class="mt-2">
           {{ form.password1 }}
          </div>
        </div>

        <div>
          <label for="id_password2" class="block text-sm font-medium leading-6 text-gray-900">Confirm Password</label>
          <div class="mt-2">
           {{ form.password2 }}
          </div>
        </div>

        <div class="mt-2">
          <button type="submit" class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Register</button>
        </div>
      </form>
    </div>
</div>

  

{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>